language: php

php:
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('secret') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -psecret
  - sudo service mysql restart

before_script:
  - mysql -e 'create database if not exists homestead;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit