language: php

php:
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - sudo mysql -e 'create database if not exists homestead;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -proot
  - sudo service mysql restart
  - sudo apt-get -y install zip wget unzip xdg-utils libxpm4 libxrender1 libgtk2.0-0 libnss3 libgconf-2-4 xvfb gtk2-engines-pixbuf xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable x11-apps
  - sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i --force-depends google-chrome-stable_current_amd64.deb
  - sudo apt-get -y -f install
  - sudo wget https://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin/


before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit